name: Jest on CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependecies
        run: npm ci

      - name: Run test
        run: npm run lint

  ci_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependecies
        run: npm ci

      - name: Run test
        run: npm test
